# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a309a3cc994fced60a80f8cc73ea4e3f66fc734fd0c355b42c4f5223b9fdd01ffb4c8ac7bdb41596a305ec2d938a9b0ba29816cb2486c8b7bb91df20f9bc8e

test:
  secret_key_base: 52be7076809d818bf38ef1680e0c4872fb326214cbb824712c4446c3d96bb64126bad0c253bc2458a5a075d4a1b15937471a691f1d43d109e81286660b15880f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
